version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:1.23
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8000:80"
    restart: always

  app:
    container_name: app
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
      - ./_docker/app/php.ini:/usr/local/etc/php/php.ini
      - ./_docker/app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - nginx
      - database

  database:
    container_name: database
    hostname: ${DB_HOST}
    env_file:
      - .env
    ports:
      - "8001:${DB_PORT}"
    image: mysql:8.0
    volumes:
        - ./_docker/tmp/db:/var/lib/mysqld
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: root
    restart: always

  adminer:
    container_name: adminer
    image: adminer
    depends_on:
      - database
    restart: always
    ports:
      - "8002:8080"
